[package]
name = "libcorebuilder"
version = "0.1.0"
authors = ["MrPeanut"]
edition = "2018"

[lib]
name = "libcorebuilder"
crate-type = ["staticlib"]

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
